apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auralis-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - auralis

  selector:
    matchLabels:
      app: auralis-backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
