apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: auralis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: auralis-oci-vault
    kind: SecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-password
