apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: auralis-oci-vault
  namespace: auralis
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-hyderabad-1.gfvleqnyaabla.abuhsljrrmksiu3m4vmq4bbqetk5el35belovhessimxr3s2ewe5xtuf7e5a
      region: ap-hyderabad-1
      principalType: Workload
      serviceAccountRef:
        name: auralis-vault-reader
