apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auralis-vault-test
  namespace: auralis

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: auralis-oci-vault
    kind: SecretStore

  target:
    name: auralis-vault-test-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-password
